### ISSUE TITLE
HOST&INTERN: Add review functionality (backend)

### ISSUE THREAD

**Issue by ashatat** [yalla-coop/presspad#113]
- [x] add review endpoint `/api/users/:id/reviews`.
  - [x] create a notification type: `getReview`.
API endpoint `API endpoint: /api/users/:id/reviews` method `POST`
payload: 
```js
  {
    to, // reviewee id
    from, // reviewer id, should be received from params and checked with authentication.
    rating, // integer
    message // string
  }
```

Relates: #50

**Comment by FarahZaqout** [comment]
Done and ready for review.

**Comment by FarahZaqout** [comment]
Added tests to pass authentication check.
@ashatat I think we should discuss how to handle the request payload.
Ramy and Abdalsamad are inclined to have it all sent in the body of the request, and not have the id sent through params.

For me I think the route would be a bit less intuitive that way, but it won't have any actual implications otherwise.
