### ISSUE TITLE
INTERN: If I selected to pay in three payments, a week before the halfway point in my tenancy I receive an email with a link to carry out the second payment

### ISSUE THREAD

**Issue by ashatat** [yalla-coop/presspad#140]

**Comment by thejoefriel** [comment]
To confirm, this will be a card payment using Stripe. Please refer to https://github.com/yalla-coop/presspad/issues/158

**Comment by OliviaPressPad** [comment]
Again - I'd make this two weeks

**Comment by RamyAlshurafa** [comment]
Hey @OliviaPressPad 
let's make an example of this scenario
today is 14th Jan and interns can't bookings until one week from today( 21th ), let's say an intern then booked 6 days with an intern from 21th to 27th, then the two weeks before the halfway will be at 10th, so this date (10th) is in the past.
so I think the locked days on the hosts' calendars should be 2 weeks instead of one, to avoid any conflicts between the dates, what do you think?
