### ISSUE TITLE
Stripe payment Question

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/presspad#158]
Hi @DarshanSB - can we get your advice please?

The team has been researching Stripe but it seems like actually it doesn't support bank transfers, which we think would be what the organizations would want rather than card payments? Is this right or is this us just misunderstanding it? If you could explain that would be great! 

Also we found this one - https://truelayer.com/ - which does seem to do bank transfers and is more reasonable than Stripe. 

What are your thoughts?

**Comment by DarshanSB** [comment]
Hi Joe

Indeed Stripe is for card payments. My thinking was if they want to do a bank transfer then they could by having the details on the invoice. Online payments are generally always there for card payments rather than bank transfers.

I haven’t used truelayer myself but back to my point above about cards vs bank transfers?

**Comment by thejoefriel** [comment]
Thanks @DarshanSB - so in your mind for this platform would the intern pay the host via card and equally the host would donate to presspad by card?

What about the organizations adding funds? How would this be handled on the platform?

**Comment by DarshanSB** [comment]
Yep. 

For organisations paying - it’s by card or by invoice. I always saw payments as mainly used by interns and hosts. Orgs, I expected would pay by card if they can (same way they would any SAAS product) or they’d go through the manual PO number > invoice > BACS route.

**Comment by thejoefriel** [comment]
Thankd @DarshanSB we'll make sure we offer solely card payment functionality then for host and intern. 

For the organisation , do you think we keep it to card at this stage? If we introduce invoices (PO etc) then I guess we would need to send admin an email that they need to raise an invoice, and we'd need to show it on the admin dashboard. Also, would we allow the org to create discount codes straight away or only once the payment goes through? Lots of orgs will have 60-90 day payment terms for invoices which may cause a cash flow issue for presspad?

**Comment by thejoefriel** [comment]
Hi @DarshanSB (and @OliviaPressPad thought you'd like confirmation on this too), here's a 
summary of what we will do:

**All transactions**
All transactions go to and from PressPad and their account. This includes:
- Intern payments for staying with a host (Intern pays PressPad)
- Host withdrawing money (PressPad pays Host)
- Host donating money (no transaction takes place, the money stays with PressPad)
- Organisation adding funds (organisation pays PressPad)

Here's an outline of what will be used for each payment flow 

**Intern payments**
- Uses Stripe and can pay by card only
- When a booking is confirmed they are offered the opportunity to pay all up front right now or in 3 parts. A payment is required then regardless. Clicking to pay will take them to a pop up with Stripe embedded where they enter their card details and click to pay

**Host withdrawing money**
- Host fills in form entering their bank details. On submit they are told they will be paid within 30 days
- Admin can view a list of payments due (including the host, the total, date withdraw was requested, host's bank details)
- Admin **manually** carries out the bank transfer
- Having completed the bank transfer admin **manually** ticks a box by the payment on the payments list to mark it as paid 

**Host donating money**
- No transaction happens as the money is already with PressPad

**Organisation adding funds**
- Uses Stripe and can pay by card only
- Clicking to add funds will take them to a pop up with Stripe embedded where they enter their card details and click to pay
- At this stage invoicing/bank transfer will not be allowed (as this introduces lots of issues we need to tackle which I've briefly outlined in my previous comment)


This can certainly be improved on in future sprints, but this will ensure all payment user stories can be completed securely. 


Please let me know by Thursday 15th August if you have any major problems with this. Otherwise we'll go ahead following this plan.

**Comment by OliviaPressPad** [comment]
Hi @thejoefriel. As you can see I'm just catching up on all this. So sorry it's taken so long but hope you got my email about our finalised January launch date which means everything relaxes a bit/we haven't lost crucial time. All of the above looks fine. My only concern (but you address it) is that"At this stage invoicing/bank transfer will not be allowed (as this introduces lots of issues we need to tackle which I've briefly outlined in my previous comment)" for organisations. The main way organisations do payment is via invoicing/bank transfer or POs (purchase orders) so it would be great to discuss ASAP how we could improve this in a subsequent sprint and get costing for that. Thanks!

**Comment by OliviaPressPad** [comment]
Re "When a booking is confirmed they are offered the opportunity to pay all up front right now or in 3 parts. A payment is required then regardless. Clicking to pay will take them to a pop up with Stripe embedded where they enter their card details and click to pay" 

I think we have to think about if they only have a short placement....I think that choosing to pay in 3 payments should only be available to those with placements of 4 weeks or longer. Is it possible to do that? Otherwise the trigger emails won't work. But if it's 4 weeks they pay the deposit (1st payment) before, the 2nd payment on the first day of the placement and the final payment mid-way/2nd week. I think that's the shortest timeframe that system would work with. I do think giving people only a week to pay isn't enough just because say you have a really busy last week and you forget then you leave your host with payments outstanding - we don't really have a way of reaching them right? Whereas we can get our coordinator to call up and chase payments if they have a 2 week window cos we have more notice on who has yet to pay. Let me know if that doesn't make sense!
