### ISSUE TITLE
Agree database schema

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/presspad#5]
Please try building models and paste in here along with your thinking

**Comment by dupreesi** [comment]
https://drive.google.com/file/d/1RO-VOupRVFyu64h7R_8pHD01eFAw2qKP/view?usp=sharing

**Comment by dupreesi** [comment]
![Bildschirmfoto 2019-05-15 um 16 45 57](https://user-images.githubusercontent.com/23721486/57784909-05727200-7731-11e9-82cc-61dbd1c2e726.png)

**Comment by RamyAlshurafa** [comment]
good job @dupreesi  :+1: 
- Does `reviews` need description/words?
- `referralCode` need status to determine if the code is used/expired?
- do we need `profileQuestion` and `questionAnswer` models? since the profile details are static maybe the `profile` is enough to store the details in: (eg. the model will contain `bio` , `pressPass`, `jobTitle`,...  directly)
- `user` need a `status` or `verified`?
- `listingAvailability` would be easier to store `unavailableDates` , the normal thing for hosts to be available in the default
- `unavailableDates` can be nested in the `listing` as an array of times
   ```js
   [ {startDate: Date,endDate: Date}] 
   ```

**Comment by thejoefriel** [comment]
This looks great @dupreesi !
And great feedback @RamyAlshurafa - agree with all of it (except one point I've raised below)

- As ramy says reviews needs a ```message``` which will store the written review 

- I also agree we can maybe just store questions in the profile directly as there aren't that many (like we'd have with a survey)

- user doesn't necessarily need status as we have ```approved``` on their profile

- I agree with @RamyAlshurafa on everything except the listingAvailability. Looking at the profile, the host is asked to write when they are available as opposed to not available so I think perhaps it would be easier to assume they're not available as the default. That way we reduce the risk of hosts being shown up in searches who aren't actually available for those dates

- as well as storing the referral code that they used to sign up we also need each user to have their own referral code they can be given out to other people to use to sign up. Are we covered on that currently? It looks like we're only storing the referral code they are given? Perhaps we make referalname actually a FK that links to a user's PK id? That way when a user is signed up they use a referral code that's linked to another user, and then while adding the new user to the database we create a new referral code for the new user so they can in turn share?

- in user we need a ```credits``` field which stores the amount of credits they have

**Comment by dupreesi** [comment]
Thanks @thejoefriel @RamyAlshurafa for your suggestions. I updated the schema accordingly and will start to build the db with some dummy data now. 
![Bildschirmfoto 2019-05-16 um 10 04 22](https://user-images.githubusercontent.com/23721486/57837039-3949a800-77c2-11e9-81d1-510062b40a81.png)
