### ISSUE TITLE
How do the organizations and interns sign up?

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/presspad#58]
Can they click to a sign up form via the landing page or do they need to be given the direct link?

**Comment by OliviaPressPad** [comment]
They can click to register/sign up on the landing page and be given a link. The hosts sign up works that in order to be accepted you have to recommend 4 other hosts so this should automatically generate an email with a link to those people to suggest they sign up. Hope that makes sense. I think we want both options though so we can send people the link when they contact us on twitter or email and ask how they sign up but also we want people to just google for themselves and find us. The link might also be handy to onboard users before we go live? If that's possible. I'm not too bothered by this and am not sure about the difference/importance of the two options so you might need to explain this to me further on the phone if I've missed the point.

**Comment by thejoefriel** [comment]
Thanks @OliviaPressPad - sorry probably being slow on this and want to make sure I understand clearly!

**ORGANSIATION**
The issue is how we ensure that not just anyone can sign up. Our initial thought was that you would manually email the organisations with a private sign up link - that way you're in control of how you do the initial beta testing with and not having to build in all sorts of verification for the organisations which we don't have any flow or wireframes for yet? What do you think?

**HOST**
So if I'm a host I click a sign up link and that takes me to a form where I can sign up, but in the form I have to add the email addresses of 4 other hosts?
Is that right? 
For those who have been directly recommended by your 'super hosts' do they need to do this too?

I guess with both of these it depends on how much you're planning to just roll out publically vs that you are user testing. We would recommend the latter at this stage, and for that you could instead send them a private link that's not on the website which means a certain level of verification has already been achieved. 

Hope that makes sense!

**Comment by thejoefriel** [comment]
This is now redundant following further changes to the platform
