### ISSUE TITLE
Legal documents

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/presspad#60]
In Trello we noticed some mentions of agreements and stuff. Are we fine to leave this at the moment? Also, do you have a clear flow/process in mind on how this would be integrated?

**Comment by OliviaPressPad** [comment]
I still need to finalise this with the lawyers. Can I do an email intro to them though so you can go direct to them with any issues. They know what kind of info we need in terms of Ts&Cs, copyright, GDPR. The other types of documents are ones that we would get users to sign in order to protect us, them, and the platform and these need to be integrated into the workflow. There are the kind of - tick box if you agree to our Ts&Cs sort of things but also fuller agreements they should be able to sign through something like Hello Sign and then that document stays on their profile so they can download it whenever. It's important that all the relevant info is attached to everyone's profiles so that it's all transparent and we can quickly - if there is a problem - know that they have signed everything etc and access those documents. I think it's also reassuring for the user to be able to see these agreements and have them accessible to look at (show Mum and Dad) whenever they like.

**Comment by thejoefriel** [comment]
Thanks @OliviaPressPad  - yeah happy for you to email us to them. I'd also be keen to have Darshan part of this discussion as well, as all of this could be a lot of added functionality we haven't currently planned for this sprint so would be good to plan it out with him and really tackle what's necessary and isn't at this first stage of prototype.
