### ISSUE TITLE
Process of approving the profile

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/presspad#62]
Is it perhaps an unnecessary step to get the host to then have to hit publish after being approved? Once their profile is approved can it not go live then and they get an email letting them know it's now live and prompting them to enter more dates they're available?

**Comment by OliviaPressPad** [comment]
It can do. What do we do though to encourage people to fill out their profiles further? I think we need to think carefully about what the minimum requirements are for approval so that people don't just think - screw this long process - I'm going to go feed the cat, and never come back! So we want them to have lovely full profiles as this is attractive on all fronts and helps facilitate good matches BUT we don't want them to have to do that all at once. So I'm fine once it's approved to immediately publish it but we need a Linkedin like thing to encourage them to fill out all parts of the profile ASAP and decide what is mandatory for approval - verification, photo, name, basic details etc.

**Comment by thejoefriel** [comment]
Thanks @OliviaPressPad - I think we can do a big push when they get their notification email reminding them to add more and you've also made a good chunk required fields (#61) which will ensure the profile is at least initially good. 

I think this is also something that will come from user testing after this initial prototype - how much do they actually come back to their profile to update / improve and how much do you need to incentivise them to do this. 

Will leave this issue open so we can continue chatting through ideas. As this can then feed into further iterations :)

**Comment by thejoefriel** [comment]
I've created a new backlog issue for this #486 so closing this now
