### ISSUE TITLE
How does the organization give the code to the intern?

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/presspad#64]
Is it a different code each time or one fixed code per organization? Ideally if we could make it one fixed code per organization that would be a lot simpler for this first iteration while not hindering overall functionality / user experience.

**Comment by OliviaPressPad** [comment]
I think it should be a unique code otherwise it could be forged. A randomized code with the initials or abbreviation of the organisation at the start would work e.g. FT_xG73N90ut (Financial Times) or CAM_oi27DF9bH (University). And the code would match to the individual intern so no one else could use it. So that code would need to be used in conjunction with the individual's name or login. Is that possible?

**Comment by OliviaPressPad** [comment]
The codes will be generated on the dashboard view next to each intern and then when the organisation is ready they can push a button that says - send code to intern and it will send to them through the internal message system of the website.

**Comment by thejoefriel** [comment]
OK thanks @OliviaPressPad - we've covered this in #36 

At the moment there won't be an internal messaging system so the intern would receive an email. Please comment on #36 if any issues or you feel there's other things we need to consider.
