### ISSUE TITLE
Where can they initially select a plan? 

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/presspad#65]
This relates to the wireframe issue #56 

Where can an organisation initially select a plan? Would it be before they go to the form when they enter email, create password etc or after?

Do you have information about each of these plans? 

No rush on this as we probably need to just default everyone to Basic at first anyway until we get to a point further down the line of integrating a payment system.

**Comment by OliviaPressPad** [comment]
Hi Joe - I think the payment system (as I wrote on another card) should be in there from the get-go. Our pitch deck (if you didn't have it before you should have! It's the most up-to-date notion of how PP functions) should help. Slide 12 shows the credit levels: https://docs.google.com/presentation/d/14SDHNbsYC5dzShGH08UcnDGIQrGo3MSfuCjYUYOC0n0/edit?usp=sharing. It's a little bit complicated but essentially you are deciding what proportion of the hosting you want to pay for. I think to make it easier though it would be good to show them how it breaks down but then basically say to them - buy credit = £100 and then you can decide how you spend it. So at the point of purchase they are just buying flat credits. But it's the point of distribution/allocation to their interns that the decision on how much of a discount they give to their interns comes. Call me tomorrow before 10am to have a chat about this because I'm making it sound more complicated than it is. 
To answer your initial question though - the organisation should create a profile and THEN buy the credit. After they have credit in their account (like a paypal) then they will be given UNIQUE codes to distribute to their interns. The interns are all on their dashboard so they would click on one - and choose to put £50 or £100 etc. towards that intern's hosting. The entry for the intern (and the org's overall credit balance) would then adjust to reflect those credits/money being spent. So - say I'm the FT, I have £1000 of credit. I want to pay for half of one intern (Joe Bloggs)'s one week internship so I would put £75 of credit next to his name. That takes my balance down to £925 and leaves Joe Bloggs to pay £75 for that week himself. Then you want to pay for the entirety of another intern's hosting because they belong to a scheme of particularly disadvantaged interns (thinking about the Guardian here who has the Positive Action Scheme and then normal work experience) and you would put £150 down for their week. Does that make sense? Call me tomorrow to chat if not.

**Comment by OliviaPressPad** [comment]
So just to add - the credit calculator will be in built and show them how they can divide up their credit and what that means but I think it should be applied individually or in bulk through selection but they don't actually subscribe to a plan at the beginning. A table would just help them understand how far their money can go and what it means for the intern in terms of what is left to pay.

**Comment by thejoefriel** [comment]
Thanks @OliviaPressPad and seen your point on #67 too - ok yeah this definitely sounds like an important thing to discuss and get Darshan's thoughts on. We'll crack on with the other stuff in the meantime, as we're not due to code next week so we've got some time to talk through all of this.
