### ISSUE TITLE
Do the interns need to be verified on signing up before being able to connect / search for hosts?

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/presspad#66]
We would recommend not (and that later down the line we build functionality for you as an admin to remove users) as this introduces an extra hurdle that might drive away take up, but just wanted to check with you on your preferred user flow.

**Comment by OliviaPressPad** [comment]
They need to be verified before they can book. So they could have an incomplete profile that is missing the things (reference, internship letter etc) that are needed to be verified and request a booking but when we filter that through to the host they might decide not to accept them cos their profile is incomplete and ultimately we can't take payment or confirm the booking until we have everything. Verification is SUPER important because the whole concept works on trust and is being trusted by both hosts and interns to have done our filtering, safeguarding and verification thoroughly so I don't think this is something we should leave til later. It needs to be hard baked into the ethos of the platform and thus the website.

**Comment by thejoefriel** [comment]
OK that's fine. So we need to have some sort of pop up when they go to click the button to book which says that they are not yet verified. 

We also need to have a button on their profile for you to click to approve them (i.e. verify them)

**Comment by thejoefriel** [comment]
This is referenced now in issue #75
